[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "esg-flight-api"
version = "1.0.0"
dependencies = [
    "flask",
    "gunicorn"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8"
]
